gitpod-io/website

src/components/Header.tsx

Implements #10.
Currently looks like this (iPhone 6/7/8 width):
Still some work left to do (e.g. fix gaps around menu, replace menu icon with cross when open) but I'd love early feedback.

[WIP][mobile] implemented mobile menu

---

src/components/GitGraph.tsx
src/components/Header.tsx
src/components/Logos.tsx
src/pages/blog.tsx
src/resources/Arrow_down.svg
src/styles/normalize.ts
src/templates/doc.tsx

Expandable table of contents in mobile menu (I also include the ToC at the bottom of the mobile Docs page, for convenience):
---
Docs page on mobile (needs a bit more padding at the top, but otherwise quite readable):
---
Docs page on mobile in landscape mode (a bit more padding left and right -- iPad in portrait looks the same):
---
iPad in landscape mode is able to show the full page (non-mobile version).

[mobile] fix docs page

---

src/components/Box.tsx
src/pages/pricing.tsx

- Using "plan" instead of "subscription"
- Using "Gitpod for teams" instead of "Team Subscriptions"
- Fixed duplicate title on PricingBoxes (notice the `p` from original title "Open Source" overflowing):
Note: This makes Box titles a little bit bigger (same size as "Gitpod for teams" box title), hope that's ok:
<details>
<summary>(old screenshot)</summary>
</details>

pricing terms

---

src/styles/normalize.ts

Before with Firefox:
Before with Chromium:
After with Firefox:
After with Chromium:

Fix double vertical scrollbar

---

src/styles/normalize.ts

I think this tiny change makes the blog even more readable (and more like Medium).
Currently:
With this change:

[blog] Reduce font-weight just a notch

---

.editorconfig
src/pages/index.tsx

I had to change the button to use an `onClick` handler as for some reason the outer `a` tag's href attrobute wasn't updated. Super strange as I could even call `{this.getBrowserExtension()}` in the contents of the button and git the correct mozilla link.
Probably some React caching that I don't understand yet. Would be really awesome to understand what's going on there, but I wanted to get a fix in now :-(

Use firefox extension link on firefox

---

src/html.js

So on start page no anchors are allowed.
Fixes gitpod-io/website#43

Rediect to gitpod.io/# if path is empty and hash is not.

---

src/docs/52_Tips_and_Tricks.md

Refers to gitpod-io/gitpod#621
This fixes a typo introduced by 332799a

Fix typo following 332799ae2a (fix of gitpod-io/gitpod#621)

---

src/docs/45_Config_Go.md

https://github.com/gitpod-io/website/blob/master/src/docs/45_Config_Go.md#L10
This definitely-gp(go-gin-app) link is wrong.
.yml was missing

fix definitely-gp link

---

src/pages/github-student-developer-pack.tsx

Removes the link in the "Claim Offer" section and fixes the mobile layout of the page.
Before:
After:

Streamline GitHub student developer pack offer

---

src/styles/normalize.ts

Fixed.  Image overlapping text issue:- Docs: **Getting Started**

---

src/pages/index.tsx

Currently, the last 2 tweets on the bottom right are collapsed and there is no spacing between them. This PR fixes that.
This is what it looks like know:

Fixes Tweet collapsing issue.

---

src/pages/education.tsx
src/pages/enterprise.tsx
src/pages/features.tsx
src/pages/recruiting.tsx
src/pages/vendor.tsx

This PR deletes section Explore Gitpod as specified in #280

deletes "Explore Gitpod" from different pages.

---

src/docs/self-hosted/0.3.0/install/01_prepare_installation.md
src/docs/self-hosted/0.3.0/install/10_install_on_kubernetes.md
src/docs/self-hosted/0.3.0/install/11_install_on_gcp_script.md
src/docs/self-hosted/0.3.0/install/34_https_certs.md
src/docs/self-hosted/0.3.0/install/35_docker_registry.md

There are some dead links and typos in the self-hosted documentation that this commit fixes. It also add some minor additions that I found useful to know while testing Gitpod self-hosted.

[self-hosted][docs] Fix some typos, dead links missing information

---

src/pages/self-hosted.tsx

The image in banner of `Self Hosted` page got replaced by `object` tag with an svg embedded (as it is in all banners now).
Fixes https://github.com/gitpod-io/website/issues/360

Replaced png with svg on Self Hosted Page.

---

src/components/TrustedBy.tsx
src/pages/enterprise.tsx
src/pages/index.tsx

[trusted-by] make FCC logo bigger for mobile devices.

---

.gitpod.yml

This PR adds vscode extensions for CSS-IN-JS support (i.e for things like IntelliSense & syntax highlighting & so on).

[setup] add: extensions for css-in-js support.

---

src/docs/julia-in-gitpod.md
src/docs/languages-and-frameworks.md
src/docs/menu.ts
src/docs/ruby-in-gitpod.md

I've simplified the Julia guide a little bit, and also moved it further down the list of languages, because the language is less popular in Gitpod and the guide is also shorter than others.
@JesterOrNot please take a look.

[docs] Small tweaks to 'Julia in Gitpod'

---

src/components/Nav.tsx

Currently, you need to click on a "Log In" button twice, which is annoying / surprising.

[nav] Make "Log In" button open Gitpod login page, not workspaces

---

src/docs/rust-in-gitpod.md

The Gitpod config I try to maintain for https://github.com/servo/servo lives in https://github.com/gitpod-io/definitely-gp/tree/master/servo

[docs] Use official Servo repository in Rust guide (instead of my personal fork)

---

src/docs/life-of-workspace.md

- The 30 days until the GC strikes is not correct and is subject to change in the future again. Removed the fixed number and pointed to the message above the workspace list.
- I have expanded the explanation a little bit in general.
- Fixed page TOC.
Bonus:
- Add typo fixes and smaller improvements to 'Live of a Workspace' page.

Improve 'Garbage Collection' text in 'Live of a Workspace'

---

src/docs/self-hosted/0.3.0/install/oauth.md

[docs] oauth change long lines of code to code blocks.

---

src/docs/vue-in-gitpod.md

Adds nuxtjs.org to example repos

[docs] add another vue.js example repository

---

src/docs/rust-in-gitpod.md

Mention the `rustup-toolchain` file :octocat:

[docs] mention a way to set the default toolchain for rust

---

src/docs/languages/cpp.md

Remove some of the excessive whitespaces from C++ language guide

[docs] remove excessive whitespace from C++ guide

---

src/blog/gitpod-launch.md
src/blog/gitpodify.md
src/docs/release-notes/2019-04-05/april-2019.md
static/release-notes/2019-04-05/april-2019.md

https://github.com/apps/gitpod-io intuitively allows configuring the app for your account or for an organization.
https://github.com/marketplace/gitpod-io doesn't, and is confusing (Gitpod is not allowed for orgs?!)

[blog][docs] Use better URL for GitHub App

---

src/docs/config-start-tasks.md

Minor fixes to start tasks documentation
- Syntax errors: both the openMode table and the openIn table had no space between the colon and the value i.e. `openMode:split-left` causes a syntax error so I replaced it with `openMode: split-left`
- Outdated section: early in the docs we say here is our setup but we have a second part of the init section, so I added it
- Minor fixes: in the before task section we have the following
```yaml
tasks:
- before: setup.sh
init: npm install
command: npm run dev
```
I sincerely doubt that `setup.sh` is in `$PATH` so I changed it to `./setup.sh`

Minor fixes to start tasks documentation

---

src/docs/languages/bash.md
src/docs/languages/go.md
src/docs/languages/html.md
src/docs/languages/python.md
src/docs/languages/ruby.md

Originally I kept all of these repositories on my personal account but to make the guide feel more official I changed the links to a gitpod-io org fork of the repositories. Also, I applied a few patches in regards to broken links.

change links from personal repo to gitpod org

---

src/docs/languages/python.md

The version numbers in the text are not in sync with Gitpod anymore. This commit changes the part to a more generic text.

[Python] Change pre-installed Python versions sentence

---

src/components/PopOver.tsx
src/components/PricingBox.tsx
src/components/pricing/PricingBoxes.tsx
src/styles/normalize.ts

Fixes gitpod-io/website#575
The same pricing box component is used in other places as well so the changes that I made are not scoped to just pricing.

[pricing] small adjustments.

---

src/docs/languages/php.md

@obasekietinosa wrote a fantastic step-by-step guide to Laravel in Gitpod:
https://notes.etin.space/posts/gitpodifying-a-new-laravel-application
I think we should add a link to it in Gitpod's PHP guide.
Many thanks Etin for powering through this, and for putting together very clear and helpful configuration steps! 💯

[docs] Add link to @obasekietinosa's Laravel guide in Gitpod's PHP guide

---

src/docs/languages/html.md

Fixes gitpod-io/website#647
This is how it looks now:

wrap: Example Repositories table in a div with the table container class

---

src/components/Nav.tsx

lock the overflow-y when the nav items are shown on mobile.

---

src/docs/languages/vaadin.md
src/docs/menu.ts

As discussed earlier with @svenefftinge, I would like to contribute Vaadin instructions to the docs section. 
I attempted to follow the same format as other docs and verified that I could run the site locally.

Add Vaadin documentation to frameworks section

---

src/docs/languages/scala.md

Experienced Scala developers wont fall for this, but it also doesn't create much confidence if the documentation proposes an ancient version of Scala :wink:

Don't propose an 8 year old version of Scala

---

src/pages/github-student-developer-pack.tsx
src/pages/github-teacher-toolbox.tsx

GitHub Education asked to add a UTM to their URL. This refers to https://www.gitpod.io/github-teacher-toolbox/ and https://www.gitpod.io/github-student-developer-pack/

Add utm to GitHub URL

---

src/docs/code-reviews.md

Newline character inside single quotes seems to be rendered verbatim, this produces an ugly line break in a very inappropriate place.

Fix ugly line break in "Code Reviews"

---

src/docs/environment-variables.md

It appears that user-defined variables beginning with the GITPOD_ prefix are discarded on workspace startup. This PR aims to document this behaviour.
Changes:
- Describes some of the default variables defined by Gitpod.
- Warns about defining new variables with the `GITPOD_` prefix.
Ideally the [Environment Variables](https://gitpod.io/environment-variables) page should disallow setting such variables since they will be ignored.
--
The wording could be improved (English is not my forte). Feedback is appreciated.

Make it clear that some environment variables are reserved

---

src/components/FeaturesSection.tsx
src/components/docs/EditInGitpod.tsx

This PR does 2 things:
- decrease the size of the EditInGitpod button. 
- reduces the spacing in careers about "Flat Hierachy".

WIP: Small fixes

---

src/pages/blog.tsx

Improve blog layout for small width screens by using `space-around` instead of `space-between` for the blog posts container

Fixes gitpod-io/website#709

---

src/docs/self-hosted/0.5.0/admin/admin.md
src/docs/self-hosted/0.5.0/install/database.md
src/docs/self-hosted/0.5.0/install/docker-registry.md
src/docs/self-hosted/0.5.0/install/domain.md
src/docs/self-hosted/0.5.0/install/helm-2x.md
src/docs/self-hosted/0.5.0/install/https-certs.md
src/docs/self-hosted/0.5.0/install/install-on-gcp-manual.md
src/docs/self-hosted/0.5.0/install/install-on-gcp-script.md
src/docs/self-hosted/0.5.0/install/install-on-kubernetes.md
src/docs/self-hosted/0.5.0/install/nodes.md
src/docs/self-hosted/0.5.0/install/oauth.md
src/docs/self-hosted/0.5.0/install/storage.md
src/docs/self-hosted/0.5.0/install/workspaces.md
src/docs/self-hosted/0.5.0/self-hosted.md

This PR copies the documentation of Gitpod Self-Hosted from [`src/docs/self-hosted/0.4.0`](https://github.com/gitpod-io/website/tree/master/src/docs/self-hosted/0.4.0) to `src/docs/self-hosted/0.5.0`.
This allows us to start editing the documentation for 0.5.0.
It is safe to merge this PR now, before the release, because 0.5.0 won't become visible on the public website unless we reconfigure the symlink [`src/docs/self-hosted/latest`](https://github.com/gitpod-io/website/tree/master/src/docs/self-hosted/) to point to the new version.

Added new version for gpsh

---

.gitmodules
src/docs/self-hosted/latest

*Note*: This depends on https://github.com/gitpod-io/gitpod/pull/1757 being merged.
Fixes https://github.com/gitpod-io/gitpod/issues/1750.
This:
- adds gitpod-io/gitpod:master as a submodule as top-level 'folder' `gitpod`
- points `src/docs/self-hosted/latest` to `gitpod/docs/self-hosted` (cmp. [gitpod-io/gitpod PR](https://github.com/gitpod-io/gitpod/pull/1757))
I maintained the current link structure under `/self-hosted/**` to a) maintain current links b) get this working quickly.

[docs] Move self-hosted documentation to gitpod-io/gitpod

---

src/docs/languages/dotnet.md

While I can see why having `mono` in the default template may be something necessary (though, TBF, I'd recommend removing it), using it shouldn't be suggested in the documentation. I've updated documentation to use .NET Core and `dotnet` CLI for building and running applications instead.

Improve .NET build and run instructions

---

src/components/gitpod-vs-codespaces/SpeedComparison.tsx
src/contents/gitpod-vs-codespaces.tsx

Looking at the new page (excellent work!) I wanted to suggest a few minor tweaks in order to slightly clarify the content:
- Title: "Loads 15x Faster" --> "15x Faster Loading"
- Graphic: "Open Project" --> "Click"
- Graphic: Turned loading phases into verbs (because they're actions), and added clarifying tooltips with sub-times
- Slightly improved the graph's footnotes
@ChristinFrohne @nisarhassan12 any thoughts/concerns? 😇

[gitpod-vs-codespaces] Minor tweaks

---

src/docs/languages/cpp.md

While exploring tinkering on a C++ project, I became a little confused on how to configure Gitpod's native extension to provide the right build configuration based on something generated by CMake. I naively assumed this would mirror VS Code's extension settings (`c_cpp_properties.json`) but this had no effect.
This PR attempts to clarify (or at least provide further reading) on how C++ currently is handled within Gitpod/Theia, and also fixes a minor typo in the link to the community forums.
Theia's C++ extension has recently been [deprecated](https://github.com/eclipse-theia/theia-cpp-extensions/commit/bb6bb9dfbc36daee0315f6f511c4c4b0fb801eef), so this may all be subject to change in future releases!

Add clarity around the C++ extension and configuration in use

---

src/docs/feature-preview.md
src/docs/menu.ts

This will re-introduce the **Feature Preview** docs originally added in https://github.com/gitpod-io/website/pull/846.
We should merge this to master as soon as the new release has been deployed on gitpod.io.
See also [relevant discussion](https://typefox.slack.com/archives/C01ELAYHVNH/p1606727350001100) (internal).
/cc @csweichel @svenefftinge

Add feature preview docs and a note about custom IDE images

---

netlify.toml
src/components/gitpod-vs-codespaces/SpeedComparison.tsx
src/contents/gitpod-vs-codespaces.tsx
src/pages/gitpod-vs-github-codespaces.tsx

Addresses parts of gitpod-io/website#841

Improve SEO for gitpod-vs-codespaces landing page.

---

src/docs/self-hosted/0.3.0/install/oauth.md
src/docs/self-hosted/0.4.0/install/oauth.md
src/docs/self-hosted/0.5.0/install/oauth.md

Replaces two occurrences of `appication` with `application` in the GitPod OAuth guide.

Correct typo in OAuth guide

---

src/layouts/docs.tsx
src/pages/blog.tsx

Addresses the following parts of #842

update meta descriptions for /blog and /docs for better SEO.

---

src/components/Nav.tsx

This will update the top navigation for `www.gitpod.io` and `docs.gitpod.io`.
1. Surface the hidden links _Docs_, _Blog_, _Community_ from the previously _Resources_ menu item.
1. Rename _Self-hosted_ to _Install_.
| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/101155648-185cd800-3630-11eb-8043-5ae255a5937a.png) | ![image](https://user-images.githubusercontent.com/120486/101155680-21e64000-3630-11eb-9585-5b4cb60d793d.png) |

Update header navigation

---

src/components/blog/SharePost.tsx

remove the extra `@` from the twitter share link.

---

src/components/Footer.tsx

Add link to Gitpod vs GitHub Codespaces Landing Page in the footer.

---

src/components/PricingBox.tsx
src/layouts/index.tsx

[pricing]: make the z-index for the buttons lower than that of the cookie consent.

---

src/components/Footer.tsx

Fixes gitpod-io/website#908
I have made the size constant for all the links sets on larger devices this is how the footer looks now:
This is how it looked before:

align the spacing in the footer.

---

src/layouts/docs.tsx

Fixes enumeration styles on `/docs/`

docs: fix enumeration styles.

---

src/pages/careers.tsx

This PR adds job profiles for 
* Senior Software Engineer (Infrastructure): Terraform, Helm, Cloud-Integration
* Senior Software Engineer (Observability): from creating metrics, logs, traces, etc. to storing and exploring them.
* Kubernetes Engineer: self-managed Kubernetes, Kubernetes integration.
* Site Reliability Engineer (SRE): master of incidents
Status:
* I'm quite happy with the role definitions.
* The tag lines can be shorter and more on-point
* The "You will be a great fit if ..." are not enough on-point.

Added job profiles related to infrastructure

---

src/components/careers/ExpandableJob.tsx

Fixes gitpod-io/website#963
I have hyphenated the titles in lowercase to be the hashes belonging to each of the sections i.e this is how the deeplinks are gonna look like for each of the job post:
#835 
- www.gitpod.io/careers/#software-engineer
- www.gitpod.io/careers/#senior-software-engineer-(full-stack)
- www.gitpod.io/careers/#senior-software-engineer-(workspace-runtime)
- www.gitpod.io/careers/#senior-devops-engineer

Create deeplinks for each of the job openings.

---

src/docs/configuration.md
src/docs/getting-started.md
src/docs/prebuilds.md
src/docs/sharing-and-collaboration.md

This idea just hit me – why not embed the new screencasts into the relevant docs sections, in order to give a quick overview of what the docs page is about.
I'm not married to the idea, but thought it could be helpful. Any feedback (for or against this) is very welcome.
Relevant URLs:
- Screencast 1 → https://deploy-preview-978--gitpod-website.netlify.app/docs/getting-started/
- Screencast 2 → (I didn't find a relevant page for "how to configure your color theme, editor, and extensions" 😬)
- Screencast 3 → https://deploy-preview-978--gitpod-website.netlify.app/docs/configuration/
- Screencast 4 → https://deploy-preview-978--gitpod-website.netlify.app/docs/prebuilds/
- Screencast 5 → ("ideal workflow" / "ephemeral workspaces"?)
- Screencast 6 → …

[docs] Embed new screencasts into relevant docs sections

---

src/docs/examples.md
src/docs/getting-started.md
src/docs/languages/deno.md
src/docs/languages/dotnet.md
src/docs/languages/go.md
src/docs/languages/javascript.md
src/docs/languages/kotlin.md
src/docs/languages/python.md
src/docs/languages/ruby.md
src/docs/languages/rust.md
src/docs/languages/scala.md
src/docs/menu.ts

[docs] Update example reposistories

---

src/components/index/Banner.tsx

This will add a secondary button to link to the new [Getting Started](https://www.gitpod.io/docs/getting-started/) section in the docs which mentions how you can use Gitpod.
**Context**: This builds on top of the original proposal in https://github.com/gitpod-io/website/issues/882#issue-759375835 and moves us one step closer to https://github.com/gitpod-io/website/issues/876.
| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/102494020-b747f200-407c-11eb-991b-4974cc784631.png) | ![image](https://user-images.githubusercontent.com/120486/102494037-bdd66980-407c-11eb-91dc-92a5ad42b588.png) |

Add getting started button

---

src/docs/github-integration.md

I am pretty sure this should read `GitHub` instead of `GitLab`.

Fix typo in docs

---

src/docs/config-start-tasks.md

There was a grammatical error [here in the gitpod docs](https://www.gitpod.io/docs/config-start-tasks/#start-tasks) .
I have correct the above by **changing *belows options* to *below options***

[docs] fix: grammatical error

---

src/docs/languages/latex.md

apparently it's 10x smaller and does the same thing?
See https://github.com/gitpod-io/gitpod/issues/1561#issuecomment-635507762
Signed-off-by: Jacob Hrbek <kreyren@member.fsf.org>

docs(LaTeX): use texlive instead of texlive-full

---

src/functions/submit-form.ts

Currently, we receive contact form emails with a bunch of SendGrid query parameters in the URLs (e.g. `?utm_campaign=sendgrid-emails&utm_source=sendgrid&utm_medium=automated_emails`).
This isn't nice, so I propose to disable the tracking on contact form submission emails.
- `tracking_settings` spec: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Request-Body-Parameters
1. Send a contact email containing a URL via https://deploy-preview-853--gitpod-website.netlify.app/contact/
2. The received email should **not** have a bunch of extra UTM parameters in the URL.

[Netlify] Disable tracking in contact form submission emails

---

netlify.toml

Relates to #999.
This PR introduces a new `/changelog` URL. At this time, `/changelog` redirects to the existing `/docs/changelog`, but provides a standardized URL format of www.gitpod.io/changelog which can be shared on social media, blog posts, etc.
A follow-up PR will address the remaining work outlined in #999.

Redirect /changelog to /docs/changelog.

---

.github/ISSUE_TEMPLATE/config.yml
SECURITY.md
netlify.toml
static/.well-known/security.txt

**currently**
1. Accessing `https://www.gitpod.io/security` or `https://www.gitpod.io/.well-known/security.txt` is 404
1. Accessing `https://gitpod.io/security.txt` functions but the hiring link in https://github.com/gitpod-io/gitpod/blob/c8526aeff02a354c1b0a5845bde07b36fa455ae6/components/dashboard/public/.well-known/security.txt is out of date.
**changes**
- Move `security.txt` into the website, resolve hiring link, add a handy redirect and resolve 404.
- https://github.com/gitpod-io/gitpod/pull/3459 implements the redirect from `https://gitpod.io/security.txt` to `https://www.gitpod.io/.well-known/security.txt`
- Wires up https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository (`SECURITY.md`)
- Creates GitHub issue template …

security: move security.txt to website from gitpod-io/gitpod
