src/components/StarGraph.tsx, src/styles/normalize.ts
[Screencast](https://youtu.be/ksuCcW4iBTw)
=> [debug] add StarGraph debug mode

src/components/ExampleBox.tsx, src/pages/index.tsx
I didn't touch the styling too much, but fixed typos and improved wordings where it made sense to me.
<details>
<summary>(old screenshot)</summary>
</details>
=> [index] misc wording and styling improvements

src/pages/pricing.tsx
Fixes #15. First pass:
<table>
<tr>
<td><strong>iPhone 6/7/8</strong></td>
<td><strong>Pixel 3</strong></td>
</tr>
<tr>
<td><img width="333" alt="iPhone 6/7/8" src="https://user-images.githubusercontent.com/599268/54749153-01642100-4bd4-11e9-9677-1c10fd62e9f6.png"></td>
<td><img width="300" alt="Pixel 2" src="https://user-images.githubusercontent.com/599268/54749186-1a6cd200-4bd4-11e9-8274-4847bf535761.png"></td>
</tr>
</table>
=> [mobile] pricing page

src/pages/features.tsx, src/pages/index.tsx, src/styles/normalize.ts
<details>
<summary>(old screenshot)</summary>
</details>
=> [mobile] index + features

src/docs/45_Config_Go.md
Part of the move to the new GOPATH
=> Updated GOPATH to reflect recent changes

src/pages/privacy.tsx
=> Updated Privacy Policy

src/components/Header.tsx
=> Added 'Community' menu entry

src/blog/prebuilds.md, src/pages/blog.tsx, src/styles/normalize.ts, src/templates/blog.tsx
I've picked values similar to what Medium uses.
Note: This also improves the Docs' readability.
=> [blog] Improved readability, nicer unambiguous dates

src/docs/40_Configuration.md, src/docs/41_Config_Gitpod_File.md, src/docs/42_Config_Docker.md, src/docs/menu.ts
Test:
- https://deploy-preview-79--gitpod-website.netlify.com/docs/40_Configuration/
- https://deploy-preview-79--gitpod-website.netlify.com/docs/41_Config_Gitpod_File/
- https://deploy-preview-79--gitpod-website.netlify.com/docs/42_Config_Docker/
=> [docs] minor wording tweaks

src/templates/doc.tsx
Fixes https://github.com/gitpod-io/website/issues/25
=> Added the edit button on docs

src/components/Footer.tsx
=> Made the Footer Responsive.

src/components/ExpandableJob.tsx, src/pages/careers.tsx, src/resources/down-arrow.svg, src/resources/up-arrow.svg
=> Fixed some edge cases.

src/pages/index.tsx
Made section "Three Ways to start coding" accessible for Keyboard Users by adding Keyboard support
=> Keyboard Navigation Fixes

src/blog/build-a-webhook-for-google-assistant.md
Hey @jankeromnes 
I moved the images to a CDN and as i can't server the images from the old url's i had to update the blog post here.
=> moved images to CDN

src/blog/build-a-webhook-for-google-assistant.md, src/docs/47_Environment_Variables.md, src/docs/release-notes/2019-02-15/february-2019.md, src/docs/release-notes/2019-04-05/april-2019.md, static/release-notes/2019-02-15/february-2019.md, static/release-notes/2019-04-05/april-2019.md
With:
```bash
rm -rf node_modules
pip install codespell
codespell -w
```
=> [minor] Fix a few typos

src/pages/github-student-developer-pack.tsx
=> Layout + text changes for student developer pack.

src/pages/index.tsx
This should hopefully help us rank better in search queries like "cloud IDE".
=> [index] Improve wording and add the word "cloud"

src/pages/github-student-developer-pack.tsx
fixes https://github.com/github-student-developer-pack/Gitpod/issues/12
=> [student pack] Rename button to "Claim Offer"

src/blog/gitpod-online-ide.md, src/pages/index.tsx
=> Updated spring example

src/blog/frictionless-oss-contributions.md
Hey @nisarhassan12, thanks for the post. I have created a PR so you can better see my proposed changes. The main proposal is to remove the complete section about how problematic setups usually are. I think this is too sidetracking. Instead I think it is good to keep the post light and positive just pointing out what contribute.dev is and how to use it.
=> Feedback contribute.dev

src/blog/frictionless-oss-contributions.md
This PR adds the teaser Image so that this post can appear in `rss.xml`.
=> Added teaser image to Announcing contribute.dev post.

package.json, src/layouts/index.tsx
This PR adds the cookie consent popup.
=> Added consent popup.

src/styles/normalize.ts, src/styles/variables.ts, src/templates/doc.tsx
I have increased the font-weight from 100 to 300 and also made a few other changes. This is what it looks like:
=> Small Improvements Docs.

src/layouts/index.tsx
=> improved cookie consent styling

src/pages/features.tsx, src/pages/index.tsx, src/utils/features.tsx
This PR addresses the following from #280
=> Features small updates/fixes.

src/components/FeatureCard.tsx, src/pages/features.tsx, src/utils/features.tsx
=> Update code review feature.

src/components/GetStarted.tsx, src/components/Project.tsx, src/components/Testimonials.tsx, src/pages/index.tsx, src/styles/normalize.ts
This PR fixes these: 
this one would work once this PR is merged! https://github.com/gitpod-io/website/pull/293
=> Home page updates

src/pages/404.tsx
This PR aligns the contents in the middle in accordance to the mockup.
this is what it looks like now:
=> 404: Make alignment of the text in accordance with the mock-up.

src/components/Quote.tsx
This PR addresses this as mentioned in #286 
This is what it looks like:
=> Adjusts spacing around the quote mobile.

src/components/Testimonials.tsx
This PR fixes this issue that is mentioned #286
=> Fixes Tweet Colapsing issue.

src/docs/31_context_urls.md
=> [docs] changed too long inline code lines to code blocks.

src/docs/32_life_of_workspace.md
=> Added info about garbage collection

src/docs/44_config_start_tasks.md, src/docs/46_prebuilds.md, src/docs/release-notes/2019-02-15/february-2019.md, src/layouts/docs.tsx, src/styles/normalize.ts
=> [docs] fixes img + table overflow issues. 

gatsby-config.js, package.json, src/components/DocSideBar.tsx, src/components/Linkset.tsx, yarn.lock
=> Added docsearch

src/docs/self-hosted/0.3.0/install/01_prepare_installation.md, src/docs/self-hosted/0.3.0/install/10_install_on_kubernetes.md, src/docs/self-hosted/0.3.0/install/11_install_on_gcp_script.md, src/docs/self-hosted/0.3.0/install/30_oauth.md
Fixing a few small things as a I follow the docs. 🙂
=> [self-hosted] Minor fixes in the docs

src/docs/menu.ts
We had some slight regression of the docs menu content w.r.t. to self-hosted. This PR fixes that.
=> [docs] Fix menu regression

src/components/GetStarted.tsx
This PR address: https://github.com/gitpod-io/website/pull/331#pullrequestreview-333785251
=> [index] input add autoFocus + add galaxy bg to the prefix in the text.

src/pages/contact.tsx, src/pages/enterprise.tsx, src/styles/normalize.ts
=> [contact] styling

src/components/Footer.tsx
This PR fixes https://github.com/gitpod-io/gitpod/issues/1016#issuecomment-567639529
=> [footer] fixes Login broken link.

src/pages/self-hosted.tsx
This PR fixes #357. 
Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
=> Make self-hosted responsive for mobile.

src/components/Banner.tsx
Fixes gitpod-io/website#360
Signed-off-by: Nisar Hassan Naqvi <syednisarhassan12@gmail.com>
=> Banner adjusts the img size.

src/components/Feature.tsx, src/components/FeatureCard.tsx, src/components/TrustedBy.tsx, src/pages/enterprise.tsx, src/pages/index.tsx
This PR addresses 3 things mentioned in #347 
* Adjusts Trustedby logos for mobile.
* Features adjusts the spacing around images for mobile.
* Made the following boxes wider for mobile:
=> Mobile fixes

src/docs/44_config_start_tasks.md
When learning the Gitpod YML file, there were a few parts of the documentation that were unclear to me.  I'm proposing resolving two of them on this page.
=> Clarifications for 'Start Tasks'

src/components/FeatureBox.tsx, src/components/GetStarted.tsx, src/components/Quote.tsx, src/components/ReadyToCode.tsx, src/pages/education.tsx, src/pages/enterprise.tsx, src/pages/features.tsx, src/pages/index.tsx, src/pages/pricing.tsx, src/pages/recruiting.tsx, src/pages/self-hosted.tsx, src/pages/vendor.tsx, src/utils/features.tsx
=> add tabIndex={-1} to make objects unfocusable.

src/docs/go_in_gitpod.md, src/docs/languages_and_frameworks.md, src/docs/menu.ts
Add Golang to languages and frameworks
see #383
=> [docs] Add Golang to Languages and Frameworks

src/components/PostPreview.tsx
=> Blog: [PostPreview] Adjust date format.

src/components/PricingBox.tsx, src/pages/pricing.tsx
=> Pricing small fixes

src/pages/pricing.tsx
Fixes #409 
This is how it looks like now:
=> [pricing] fixes broken layout issue.

src/components/PopOver.tsx
=> [Popover]: add keyboard support.

src/styles/normalize.ts
=> [accessibility] add focus styles for interactive elements.

src/components/DropDown.tsx, src/components/ExternalLink.tsx, src/components/Nav.tsx
=> Fixes #394

src/components/GetStarted.tsx, src/pages/pricing.tsx, src/styles/normalize.ts
This is how it looks like now:
=> [pricing] update messaging.

src/layouts/index.tsx, src/styles/normalize.ts
=> remove the foucs at onClick & and have it too for keyboard users.

src/docs/rust-in-gitpod.md
=> Minor spell check for rust in gitpod

src/pages/about.tsx
=> [about] fix broken careers link.

src/pages/index.tsx
=> Fixes gitpod-io/website#437

src/docs/python-in-gitpod.md
So minor tweaks to python-in-gitpod including a reference to help with Python GUI applications
=> Minor tweaks to python-in-gitpod

src/pages/enterprise.tsx
=> [enterprise] remove SLA popover + replace "Optional" with a check.

src/components/ExternalLink.tsx, src/components/Nav.tsx, src/components/PricingBox.tsx, src/layouts/docs.tsx, src/pages/index.tsx, src/templates/blog.tsx
=> Fixes [mobile issues] #413

src/docs/go-in-gitpod.md, src/docs/ruby-in-gitpod.md, src/docs/rust-in-gitpod.md, src/layouts/docs.tsx
=> [docs] small fixes for mobile.

src/docs/prebuilds.md
Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>
=> prebuilds: Add method to trigger prebuild using URI

src/pages/contact.tsx, src/pages/pricing.tsx
Messaging for Students subscriptions seemed to be too complicated. 
Button had no purpose
=> [pricing] adjust wording & delete "student" button

src/components/PricingBox.tsx, src/pages/index.tsx, src/styles/normalize.ts
=> update hover styles for buttons.

src/docs/python-in-gitpod.md
Enhance some wording :octocat:
=> [docs] fix wording for python-in-gitpod

src/docs/config-docker.md
- Use the typical `.gitpod.Dockerfile` file name
- Remove deprecated usage of `USER root`
- Fix `apt-get` snippet
=> [docs] Improve config-docker.md

src/docs/menu.ts, src/docs/unlimited-open-source.md, src/pages/pricing.tsx
[docs] add requirements for the "unlimited open-source plan" #453
=> Adding unlimited-open-source section to docs #453

src/docs/config-docker.md
This is a copy of #116 as this is easier than to fix merge conflicts
=> [docs] state dockerfile requirements

src/docs/rust-in-gitpod.md
Specify how to use rustup in a Dockerfile
=> [docs] specify how to use rustup in a Dockerfile

src/docs/go-in-gitpod.md
This is to keep the guides consistent ❤️
=> Change header from `Go` to `Go in Gitpod`

src/components/PricingBox.tsx, src/pages/github-student-developer-pack.tsx
=> [github-student-developer-pack] small updates.

src/docs/bash-in-gitpod.md, src/docs/cpp-in-gitpod.md, src/docs/go-in-gitpod.md, src/docs/python-in-gitpod.md, src/docs/ruby-in-gitpod.md, src/docs/rust-in-gitpod.md
Make the languages and frameworks more accessible to blind people by adding alts to images so that text readers can tell the reader what the image is of!  :octocat:
=> [docs] make languages-and-frameworks more accessible

src/docs/menu.ts
=> [docs] Move languages and frameworks above theia

src/docs/python-in-gitpod.md
=> [docs] Patch python version section

src/docs/ruby-in-gitpod.md
@JesterOrNot please take a look when you have time. 🙂
=> [docs] Add Rails Sample App to Ruby examples

src/components/FeatureBox.tsx, src/components/ScrollToTopButton.tsx, src/pages/features.tsx, src/resources/vsc-grey.svg, src/utils/features.tsx
Fixes #369 
This is how it looks now:
=> Fixes #369

src/docs/php-in-gitpod.md
Add div to make the PHP more responsive on mobile
=> [docs] make PHP guide responsive on mobile

src/components/Nav.tsx
I'm not too sure! but I think this will fix the SRR issue.
Fixes #483
=> fix the SSR issue

src/blog/developing-nuxtjs-in-browser.md, src/blog/docker-in-gitpod.md, src/blog/gitpodify.md, src/docs/checkout-location.md
(Needs to be double-checked & tested.)
=> [docs] Simplify .gitpod.yml tasks syntax

src/docs/python-in-gitpod.md
A few minor tweaks to grammar and spelling.
=> [docs] grammar edits for `Python in Gitpod`

src/components/DropDown.tsx, src/components/Nav.tsx
=> [Nav] add login button to the side of the hamburger on mobile. 

src/components/Nav.tsx, src/components/PricingBox.tsx
=> [PricingBox] add the missing tick icon to the list items.

src/docs/bash-in-gitpod.md, src/docs/cpp-in-gitpod.md, src/docs/go-in-gitpod.md, src/docs/php-in-gitpod.md, src/docs/python-in-gitpod.md, src/docs/r-in-gitpod.md, src/docs/ruby-in-gitpod.md, src/docs/rust-in-gitpod.md, src/docs/vue-in-gitpod.md
=> [docs] Make links languages and frameworks section more obvious

README.md, gatsby-config.js, src/components/ReadyToCode.tsx, src/layouts/docs.tsx, src/layouts/index.tsx, src/pages/blog.tsx, src/pages/education.tsx, src/pages/enterprise.tsx, src/pages/features.tsx, src/pages/github-teacher-toolbox.tsx, src/pages/index.tsx, src/pages/pricing.tsx, src/pages/recruiting.tsx, src/pages/vendor.tsx, src/utils/features.tsx
This PR address the followinf from #372
=> add meta descriptions

gatsby-config.js, package-lock.json, package.json, src/docs/README.md, src/docs/config-theia.md, src/docs/menu.ts, yarn.lock
Fixes: https://github.com/gitpod-io/gitpod/issues/1279
@felipecassiors: Feedback is appreciated :)
=> [docs] theia configuration

src/components/GetStarted.tsx, src/components/Quote.tsx, src/components/ReadyToCode.tsx, src/pages/education.tsx, src/pages/enterprise.tsx, src/pages/features.tsx, src/pages/github-student-developer-pack.tsx, src/pages/github-teacher-toolbox.tsx, src/pages/index.tsx, src/pages/pricing.tsx, src/pages/recruiting.tsx, src/pages/self-hosted.tsx, src/pages/vendor.tsx, src/utils/features.tsx
=> add alt text to objects.

src/styles/normalize.ts
=> adjust spacing between the buttons.

src/pages/github-student-developer-pack.tsx, src/pages/github-teacher-toolbox.tsx
=> [github-teacher-toolbox] adjust the quote.

src/docs/cpp-in-gitpod.md
One link still had the backticks
=> Make a link more readable

src/docs/bash-in-gitpod.md, src/docs/cpp-in-gitpod.md, src/docs/go-in-gitpod.md, src/docs/html-in-gitpod.md, src/docs/julia-in-gitpod.md, src/docs/ruby-in-gitpod.md, src/docs/rust-in-gitpod.md, src/docs/vue-in-gitpod.md
Make an effort to make languages and frameworks more consistent
=> [docs] Make the examples sections more consistent

src/docs/languages/php.md
Make the example repo repository field links
=> [docs] Linkify PHP example repo links

src/docs/languages/bash.md, src/docs/languages/cpp.md, src/docs/languages/dotnet.md, src/docs/languages/go.md, src/docs/languages/html.md, src/docs/languages/java.md, src/docs/languages/php.md, src/docs/languages/python.md, src/docs/languages/r.md, src/docs/languages/ruby.md, src/docs/languages/rust.md, src/docs/languages/vue.md
Fix images for languages and frameworks section
=> [docs] Fix images

src/docs/languages/rust.md
Fix one more image in languages and framewors
=> [docs] fix last image

src/docs/workspaces.md
=> [docs]: Workspaces update contents to be more precise.

src/docs/languages/dotnet.md, src/docs/languages/go.md, src/docs/languages/html.md, src/docs/languages/python.md, src/docs/languages/rust.md, src/docs/languages/vue.md
=> [docs] fix misc. grammar and punctuation.

src/docs/browser-extension.md
it looks weird with the "and" here
=> docs/browser-extension: Removed 'and'

src/docs/self-hosted/0.3.0/install/install-on-kubernetes.md
=> Make a few fixes in the self-hosted docs

src/components/features/FeatureBox.tsx, src/components/features/FeaturesList.tsx, src/components/features/Intro.tsx, src/pages/features.tsx
Fixes #562 
This is how the features page looks now:
=> Fixes #562

src/docs/frameworks/pandas.md, src/docs/languages-and-frameworks.md, src/docs/menu.ts
Add a Pandas Frameworks Guide! See #383
=> [docs] Add Pandas To Frameworks Section

.gitpod.yml
This is in response to https://github.com/gitpod-io/website/pull/565#discussion_r401675905
=> Change openMode for plugin terminal to tab-after

src/docs/languages/rust.md
=> [docs] Add a section on Rust debugging to the Rust guide

src/components/TrustedBy.tsx, src/pages/enterprise.tsx, src/pages/index.tsx
Fixes https://github.com/gitpod-io/website/issues/594
=> Update 'Trusted by' logos

src/blog/native-ui-with-vnc.md, src/docs/release-notes/2019-02-15/february-2019.md, static/release-notes/2019-02-15/february-2019.md
In preparation for https://github.com/gitpod-io/workspace-images/pull/215
=> [docs][blog] Update gitpod/workspace-full-vnc Dockerfile examples

src/docs/menu.ts
=> [self-hosted] make all links visible in menu

src/components/NewsletterForm.tsx, src/pages/contact.tsx, src/styles/normalize.ts
=> Make button styles consistent.

src/components/index/WhyGitpod.tsx, src/docs/index.md
I made some grammar edits to the index page
* Made sentences clearer.
* Fixed a few comma based grammar issues
=> [docs] Fix some more grammar mistakes

src/blog/gitpod-self-hosted-0.4.0.md, src/templates/blog.tsx
=> adjust the admin ui screenshot.

src/docs/configuration.md
... in "Configure Your Project" section.
=> Add missing "and"

src/components/pricing/Plans.tsx, src/components/pricing/PricingBoxes.tsx, src/components/self-hosted/Feature.tsx, src/components/self-hosted/Features.tsx, src/pages/pricing.tsx
Fixes #624
This is how they look now:
=> [pricing] adjust the plans

src/docs/languages-and-frameworks.md, src/docs/languages/kotlin.md, src/docs/menu.ts
=> [docs] Kotlin in Gitpod

src/docs/languages/html.md
=> [docs]: HTML/CSS fix the rendering of the subtitle.

src/docs/README.md, src/docs/code-reviews.md, src/docs/config-ports.md, src/docs/git.md, src/docs/ide.md, src/docs/languages/dotnet.md, src/docs/languages/html.md, src/docs/languages/julia.md, src/docs/languages/kotlin.md, src/docs/languages/php.md, src/docs/languages/r.md, src/docs/pull-requests.md, src/docs/search.md, src/docs/sharing-and-collaboration.md, src/docs/teams.md, src/docs/tips-and-tricks.md
=> [docs]: add missing alt texts.

src/components/pricing/SelfHostedFAQs.tsx
=> [pricing]: Self Hosted FAQs fix the broken link.

src/docs/languages/bash.md
Follow-up-on: https://github.com/gitpod-io/gitpod/issues/1461
Signed-off-by: Jacob Hrbek <kreyren@member.fsf.org>
=> Bash: Documentation for known issue

src/components/ReadyToCode.tsx, src/components/index/WhyGitpod.tsx, src/pages/about.tsx, src/pages/pricing.tsx, src/pages/self-hosted.tsx, src/utils/features.tsx, src/utils/recruiting.tsx, src/utils/vendor.tsx
=> [site] Grammar fixes

src/blog/build-a-webhook-for-google-assistant.md, src/blog/continuous-dev-environment-in-devops.md, src/blog/dev-env-as-code.md, src/blog/developing-nuxtjs-in-browser.md, src/blog/docker-in-gitpod.md, src/blog/frictionless-oss-contributions.md, src/blog/github-flow.md, src/blog/gitlab-support.md, src/blog/gitpod-launch.md, src/blog/gitpod-online-ide.md, src/blog/gitpodify.md, src/blog/local-services-in-gitpod.md, src/blog/native-ui-with-vnc.md, src/blog/node-js-development.md, src/blog/node-js-gitpod.md, src/blog/october-2018-release.md, src/blog/prebuilds.md, src/blog/status-page.md, src/blog/update-december-2019.md, src/blog/when-code-reviews-lgtm.md, src/blog/workspace-snapshots.md
=> [blog]: add missing alt text + update exisiting ones to be more precise.

src/docs/search.md
=> Fix typo in "Search" section

src/docs/self-hosted/0.4.0/install/domain.md
Fixes https://github.com/gitpod-io/self-hosted/issues/21
=> [self-hosted] Fix subdomain example

src/components/blog/PostBanner.tsx, src/templates/blog.tsx
=> Remove the weird spacing from the top of Post Banner Image.

src/templates/blog.tsx
=> add meta preview to the blog posts.

src/docs/gitlab-integration.md
=> [docs] temporarily removed native gitlab docs

src/docs/browser-extension.md, src/docs/github-integration.md, src/docs/gitlab-integration.md
=> [docs] gitlab oauth provider

src/components/pricing/PricingBoxes.tsx, src/pages/enterprise-license.tsx
=> add "Domain Name" form field + other small correction and updates to the license key page.

src/pages/self-hosted-terms.tsx
source: https://github.com/gitpod-io/gitpod/blob/master/License.enterprise.txt
=> [self-hosted] add terms

src/components/AnnouncementBanner.tsx, src/components/Banner.tsx, src/components/DropDown.tsx, src/components/FeatureCard.tsx, src/components/PricingBox.tsx, src/components/features/StarFortFree.tsx, src/components/index/Banner.tsx, src/components/index/TextFeature.tsx, src/components/pricing/PricingBoxes.tsx, src/components/pricing/PricingFAQs.tsx, src/layouts/docs.tsx, src/styles/base.ts
=> Mobile improvements

src/docs/gitlab-integration.md
=> [docs] native gitlab (DON'T MERGE)

src/contents/features.tsx
=> Deletes duplicate

src/layouts/index.tsx
=> disable the open source announcement banner.

src/pages/careers.tsx
Updates the job offer for a Platform Security Engineer
=> Fixes gitpod-io/website#796

src/docs/languages/javascript.md
=> document How to make live reload work in Rollup based projects like Svelte

src/components/PricingBox.tsx, src/components/pricing/PricingBoxes.tsx
=> [pricing]: add per user/month to the cloud plans.

src/components/Arrow.tsx, src/components/Footer.tsx, src/components/careers/ExpandableJob.tsx, src/components/docs/ReachOut.tsx
=> improve icons.

src/contents/gitpod-vs-codespaces.tsx, src/contents/index.tsx
=> add missing alt texts.

src/docs/feature-preview.md, src/docs/menu.ts
This will add relevant documentation for the **Feature Preview** settings added in https://github.com/gitpod-io/gitpod/pull/2171.
=> Add Feature Preview documentation

src/docs/configuration.md
=> configuration.md: for your dev environment

src/docs/languages-and-frameworks.md, src/docs/menu.ts
=> Fix links on Languages & Frameworks

src/components/gitpod-vs-codespaces/PowerComparison.tsx
=> adjust resource graphic for mobile.

src/blog/gitpod-and-github-codespaces.md, src/blog/local-services-in-gitpod.md, src/blog/native-ui-with-vnc.md, src/blog/prebuilds.md, src/blog/status-page.md, src/contents/authors.ts
update chris' github user name
Fixes gitpod-io/website#885
=> [blog] Update around GH CS

src/blog/moving-software-development-to-the-cloud.md
I rewrote the blog post adjusting our tone a bit and moving the message more from "Gitpod vs GitHub" to "Moving software development to the cloud together"
=> Adjusted blog post for Univers w. context/links/ bold text

src/blog/moving-software-development-to-the-cloud.md
Follow-up from https://github.com/gitpod-io/website/pull/891.
=> Fix broken blog post link to docs

src/docs/getting-started.md, src/docs/index.md
To have a more linear reading/onboarding flow within our docs I added a Next Steps section for the Getting Started Guide.
=> [docs] Added Next Steps section

src/components/Bg.tsx, src/pages/education.tsx, src/pages/recruiting.tsx, src/pages/vendor.tsx
Addresses the following from #842
=> add missing alts to make SEO better.

src/docs/bitbucket-integration.md, src/docs/gitlab-integration.md, src/docs/languages/dart.md, src/docs/languages/java.md
addresses the following from gitpod-io/website#842
=> [docs]: SEO correct the links to fix the Page not found issue.

src/components/Nav.tsx
Fixes gitpod-io/website#881
BEFORE | AFTER  
-- | --
=> collapse to burger menu at a smaller breakpoint.

src/components/PopOver.tsx, src/components/PricingBox.tsx
=> make the cards tall in accordance to their content height for small devices.

src/docs/config-ports.md
This feature was introduced by https://github.com/gitpod-io/gitpod/pull/1909
=> Add section about port visiblity

src/docs/menu.ts
=> [docs] Update for 0.6.0

src/pages/careers.tsx
Fixed the typos (we definitely had too many of them). Next time we should paste the text in Google Docs to run some spell checks over it (or maybe there is some spell checking VS Code Extension 🙃)
=> Fixed typos

src/components/AnnouncementBanner.tsx
=> fix: Job opening banner isn't visible issue on Chrome.

src/components/Nav.tsx
=> Clean up Nav.

src/contents/projects.tsx, src/docs/examples.md, src/docs/languages/svelte.md
https://github.com/gitpod-io/sveltejs-template
Preview:
- https://deploy-preview-994--gitpod-website.netlify.app/docs/examples/
- https://deploy-preview-994--gitpod-website.netlify.app/docs/languages/svelte/#example-projects
=> [docs] Add SvelteJS example repository

src/components/AnnouncementBanner.tsx, src/pages/self-hosted.tsx, src/styles/variables.ts
Fixes gitpod-io/website#977 #992 
=> Improve Design and Accessibility for the Banner. 

src/blog/gitlab-support.md, src/components/pricing/PricingFAQs.tsx, src/contents/enterprise.tsx, src/docs/release-notes/2019-04-05/april-2019.md, src/pages/contact.tsx, src/pages/education.tsx, src/pages/enterprise-license.tsx, src/pages/enterprise.tsx, src/pages/recruiting.tsx, src/pages/self-hosted.tsx, src/pages/vendor.tsx, static/release-notes/2019-04-05/april-2019.md
Also a few drive-by SEO fixes.
=> Refresh contact subjects & links

src/pages/contact.tsx
Currently the layout for the contact form is a bit broken this Pr fixes that With the changes in place this is how it looks:
=> fix the contact form layout.

src/components/AnnouncementBanner.tsx
Addresses the remaining feedback on https://github.com/gitpod-io/website/pull/984
| Before | After |
| - | - |
|![image](https://user-images.githubusercontent.com/46004116/107824231-f48ddf00-6da2-11eb-9b0f-a53bbdbe82ea.png)| ![image](https://user-images.githubusercontent.com/46004116/107824898-015f0280-6da4-11eb-8600-a2c71b3d6831.png)|
|![image](https://user-images.githubusercontent.com/46004116/107824986-26ec0c00-6da4-11eb-899b-3023043a47bf.png)|![image](https://user-images.githubusercontent.com/46004116/107825051-4125ea00-6da4-11eb-88cf-dc02c68984c1.png)|
=> adjustments banner small improvements.

src/pages/contact.tsx
New proposed subjects:
- Question about Gitpod Self-Hosted
- Question about Gitpod's Paid Plans
- Applying for the Custom IDE Beta
- Applying for Professional Open Source
- Student Unlimited: Get Verified as a Student
- Other
Self-help links:
- [Professional Open-Source eligibility](https://www.gitpod.io/docs/professional-open-source/)
- [Ask the Gitpod Community](https://community.gitpod.io/)
=> [contact] Update contact page options

src/docs/prebuilds.md
Supercedes PR https://github.com/gitpod-io/website/pull/959 by @j0nes2k (thank-you!)
=> docs: split prebuild instructions on a per hosting platform basis

README.md
Fixed incorrect spacing typos
Fixes gitpod-io/website#1012
=> Fixed incorrect spacing typos

src/components/SubmissionSucess.tsx
=> Change the wording in SubmissionSuccess.tsx

src/blog/build-a-webhook-for-google-assistant.md
will address the following from #842 :
=> [SEO]: fix page not found(external links).

src/docs/languages/dotnet.md
Clarification related to discussions at https://community.gitpod.io/t/debugging-net-unit-tests/2928/5
=> docs: clarification that the MSFT debugger is proprietary

src/docs/languages/dotnet.md
Merge when https://github.com/gitpod-io/workspace-images/pull/378 is merged.
=> docs: add reference to dotnet lts images
